## Filtering on covariates

Simple spatial and temporal filters are agnostic to any correlation between the status of a tracking system and the extent of error. However, both may be refined by consulting tracking system metadata, i.e., data on the status of the tracking system itself, which can be a good indicator of the reliability of calculated positions. For example, at a broad scale the number of active receivers in an ATLAS system can indicate time periods when a system suffers a malfunction and thus collects unreliable data; these ‘down times’ can form the basis of a temporal filter. Similarly, data from system tests may reveal regions of the study area in which the system’s localisations are error-prone, and can inform an explicit spatial filter. At smaller scales the observation-specific metadata may be used to filter out locations which fail to meet a certain cutoff. For example, ATLAS systems calculate animal positions using the times of arrival of a radio transmission from each tag to multiple receiver stations. The number of receiver stations involved in each localisation is considered to be an indicator of data quality, and positions localised using fewer than three receivers (the minimum required for an ATLAS localisation) can be excluded. 

Further, tracking systems often yield internal measures of positioning error which are based on the dilution of precision. ATLAS and other time-of-arrival systems calculate positioning error in two dimensions (MacCurdy et al. 2009), while other systems may yield a three dimensional positioning error. Positioning error is an intuitive criterion by which to filter data, and this takes the form of locations with an estimated error above a certain threshold being excluded. There are two other ways of dealing with positioning errors, and of these the aggregation of positions over a time interval is discussed below. The more demanding method is to model the animal’s movement, for example, in a continuous time movement model (Calabrese et al. 2016; Noonan et al. 2019). Movement model methods can use the positioning error from the tracking system, in conjunction with calibration data, to estimate the real individual position and movement distances between positions. However, movement model methods are computationally intensive, make several assumptions about animal movement, and can be challenging to implement for the beginning practitioner, and are not discussed further.
