# Cleaning movement tracks

## Filtering on speed and turning angle

Since the phenomenon represented by data from animal tracking studies is movement, it is appropriate and necessary to examine whether individual trajectories obtained by joining positions remaining from previous filtering steps are realistic. This is often a subjective assessment based on expert judgement of the observed movement tracks, which presents two main problems: first, subjective assessments are difficult to reproduce, which hampers consistent analyses across tracking periods. The second issue is that manual identification and correction of problematic trajectories is prohibitively time consuming when dealing with high volumes of data. The solution to both problems is to employ a hybrid approach, in which experts manually examine a subset of movement tracks (rather than positions) and attempt to identify common problems with the trajectories. Experts can then conceptualise an algorithm by which problematic sections of a trajectory may be removed, and automate the application of this algorithm to the wider dataset, under the assumption that the subset used to define the algorithm was representative of the full data.

Algorithms for filtering trajectories are different from those for filtering point locations in that they commonly filter on derivative variables, i.e., the instantaneous change in some variable with respect to another variable. The two most common derivative variables are speed, the change in position in unit time, and turning angle, the change in heading in unit time. Trajectories must always be checked for correct temporal ordering before calculating metrics with time interval as a denominator. Speed and turning angle filters should be applied in a stepwise fashion, and it is safest to first apply a simple speed filter that removes positions with instantaneous speeds above a certain threshold. This threshold should be informed by the tracked animal’s biology, but it is also important to consider that high frequency tracking typically overestimates the speed between positions due to positioning error (Ranacher et al. 2016; an explanation for animal tracking data is given in Noonan et al. 2019). Even assuming data with large positioning errors have been removed, it is advisable to begin with a liberal speed threshold that excludes only the most unlikely of movements.

Speed filters have the drawback of removing at twice as many positions as strictly necessary (the speed duplication problem). For example, in a trajectory of three positions (p1, p2, and p3), the outlier p2 has a high instantaneous speed, as does the ‘real’ position p3, whose displacement is calculated relative to the outlier p2; both will be removed by the same speed filter. Speed filtering with low thresholds also risks losing valid data on fast transit behaviour of a study species, and this is especially a risk for aerial transit which can be strongly assisted by winds. In such cases, turning angle filters can help distinguish between high instantaneous speeds arising from positioning error and those that comprise a fast transit segment. Most animals are physiologically constrained to move quickly only in relatively straight lines, i.e., with low turning angles, and large turning angles coupled with high speeds often represent positioning errors in the data, whereas high speed - low angle positions are likely to capture extreme yet real movements.

## Challenges to speed filters

A more serious challenge to speed filters is the tracking system phenomenon of ‘reflected’ positions, in which the estimated location is instantaneously displaced many hundreds of metres from the individual’s real position for some time, followed by a return to a location near the real position. In such a ‘reflection’ comprised of the positions t1...tr, p1...pn, and tr+1...tn where positions denoted by t represent real trajectory positions, and those denoted p represent reflected data a great distance from the real trajectory, the positions p1 and tr+1 will have very high instantaneous speeds. A speed filter applied to such reflected data would only remove p1 and tr+1, leaving the positions p2...pn, which are erroneous and must be removed. Iteratively applying a speed filter to this data while recalculating speeds in each iteration until no extreme speeds remain is an imperfect solution, since it will remove valid positions tr+i for each erroneous position pi; the true scale of the speed duplication problem is thus revealed. Another approach to identifying reflections and especially to determining where they end is to identify the first position with extreme speeds (p1), and calculating the speed between the preceding position (tr) and all subsequent positions (p1...tn) until the first position with a realistic instantaneous speed relative to tr is located; in this case tr+1. The drawback here is that the method is sensitive to the duration of the reflection, since the speed between tr and subsequent (reflected) positions will decrease exponentially to a realistic value over time (as the denominator time increases), and the algorithm will prematurely consider the reflection to have ended.

A more heuristic approach to dealing with trajectory reflections involves using the phenomenon’s properties to identify its bounds, and removing all positions between these bounds. The first step is identifying anomalous positions with extreme speeds and turning angles, as in the point outlier case. The trajectory can then be split into pre- and post-anomaly segments, and the first position of the post-anomaly segment, which is the inner bound of the reflection, can be set as an anchor point. The first position after the anchor point with an instantaneous speed >= the anchor point can be considered to be the upper bound of the reflection, and lacking such a position, the position with the next greatest instantaneous speed can be considered the outer bound of the reflection. The positions between these bounds can be identified as a trajectory reflection and removed. To prevent the algorithm from searching through many hundreds of thousands of data points, the algorithm can be set to consider a post-anomaly segment of K positions, and to look for the end of the reflection within this bound. 

While fast, the drawback with this method is in the simplicity of its assumptions that (1) the first position of the data is correct and not itself a reflection, (2) the reflection ends within K positions, and (3) the individual is not moving towards the reflected positions. Violation of any of these assumptions will cause the method to fail catastrophically: (1) if the first position is a reflection, it will be preserved and real positions will be removed, (2) if the reflection does not end within K positions the algorithm will erroneously assign the highest speed within K positions as the end, and (3) the individual’s real positions overlapping with the reflected positions will result in low speeds between erroneous and real positions, leaving the algorithm unable to find the correct reflection end. If reflections persist in the data after this procedure, or are so prevalent as to cause the algorithm to return erroneous data, there is a limited number of options: (1) attempt to identify whether reflections occur in a common area across individual tracks, and manually identify and remove positions from within the bounds of these so-called ‘attractor points’, (2) subset the data and discard subsets which have more than N anomalous speed-angle positions, as these may indicate many reflected segments, or (3) identify anomalies and remove positions within some time limit of each anomaly, in the hope that the reflection ends by that time.
