# Smoothing positioning errors

## The median smooth

While the filters described so far are sufficient to remove serious positioning errors, careful examination of the resulting trajectories may reveal that smaller positioning errors remain – the trajectory appears ‘spiky’ at small scales. These smaller errors are usually more challenging to remove since they have covariates (such as speed and turning angles) which are within the expected range of movement behaviour for the study species, hence their persistence in the data. The high volumes of data generated by high frequency tracking studies can be brought to bear upon this issue, by smoothing the trajectory. A ‘smooth’ works by approximating the true value of an observation based on neighbouring values. A common and easily implemented smoothing technique is nearest neighbour averaging, in which the value of an observation X0 is the average of some K nearest neighbours. 

The median smooth (confusingly also called the median filter) is a variant of nearest neighbour averaging which replaces X0 with the median of its neighbours, and this is recommended over simple averaging as it is robust to outliers. A median smooth with an appropriate smoothing window (usually 3 – 5 positions) centred on each observation can be applied to the X and Y coordinates of the trajectory to obtain a smoothed track. The median smooth will return as many smoothed coordinates as there are observations in the data, and does not interpolate between positions when data are missing. However, it is robust to even very large gaps, and it is not necessary to split the data into segments separated by periods of missing observations when applying the filter.
